# plot_fig3.py
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from functions import get_ensemble_stats_with_variance, calculate_lifetime_with_error_propagation

def main():
    # --- 1. Data Configuration (Using relative paths for GitHub) ---
    # These directories should contain the CSV files generated by your processing scripts
    dir_early = './processed_results/'
    dir_late = './processed_results_2200/'
    
    try:
        # Load ensemble statistics (mean and variance) for both time horizons
        # Pre-2100 (11 models) and Post-2100 (5 models)
        ts_early_mean, ts_early_var = get_ensemble_stats_with_variance(dir_early, "*_ts.csv")
        ts_late_mean, ts_late_var = get_ensemble_stats_with_variance(dir_late, "*_ts_to2200.csv")
    except Exception as e:
        print(f"Error loading data: {e}")
        print("Ensure processed CSV files are in the correct relative directories.")
        return

    # Define birth cohorts for analysis (1950 to 2120 every 10 years)
    display_years = list(range(1950, 2121, 10))

    # Initialize data structures
    results = {'0-5':[], '5-9':[], '10-19':[], '20-54':[], '55-59':[], '60-75':[]}
    total_days = []
    total_errors = []
    aged_exposure = []
    aged_errors = []

    # --- 2. Cohort Processing & Error Propagation ---
    for b_year in display_years:
        # Calculate full lifetime metrics using the propagated error law defined in functions.py
        t_mean, t_sd, day_list = calculate_lifetime_with_error_propagation(
            b_year, ts_early_mean, ts_early_var, ts_late_mean, ts_late_var
        )
        
        if not day_list:
            continue

        # Segment lifetime data into specific age groups
        results['0-5'].append(sum(day_list[0:6]))      # Childhood
        results['5-9'].append(sum(day_list[6:10]))
        results['10-19'].append(sum(day_list[10:20]))
        results['20-54'].append(sum(day_list[20:55]))  # Adulthood
        results['55-59'].append(sum(day_list[55:60]))
        results['60-75'].append(sum(day_list[60:76]))  # Aged
        
        total_days.append(t_mean)
        total_errors.append(t_sd)
        
        # Specific error propagation for the 'Aged' stage (60-75)
        v_sum_aged = 0
        for age in range(60, 76):
            yr = b_year + age
            v_sum_aged += ts_early_var.loc[yr] if yr <= 2100 else ts_late_var.loc[yr]
        
        aged_exposure.append(sum(day_list[60:76]))
        aged_errors.append(np.sqrt(v_sum_aged))

    # --- 3. Plotting Configuration ---
    plt.style.use('seaborn-v0_8-white')
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(16, 14), 
                                   gridspec_kw={'height_ratios': [2, 1]}, 
                                   facecolor='white', dpi=300)
    plt.subplots_adjust(hspace=0.25)

    x = np.array(display_years[:len(total_days)])
    X_WIDTH = 7
    LABELS = ['0-5', '5-9', '10-19', '20-54', '55-59', '60-75']
    COLORS = ['#ffeda0', '#fed976', '#feb24c', '#fd8d3c', '#f03b20', '#bd0026']

    # --- 4. Panel A: Full Life Cycle Stacked Exposure ---
    bottom_val = np.zeros(len(x))
    bars = []
    for i, label in enumerate(LABELS):
        b = ax1.bar(x, results[label], width=X_WIDTH, bottom=bottom_val, 
                    color=COLORS[i], edgecolor='white', lw=0.3)
        bars.append(b)
        bottom_val += np.array(results[label])

    # Error bars represent the multi-model uncertainty (1 SD)
    ax1.errorbar(x, total_days, yerr=total_errors, fmt='none', 
                 ecolor='#333333', elinewidth=1.2, capsize=4, zorder=10)

    # Segmented Legend
    LEGEND_Y = 1.05
    l1 = ax1.legend(bars[:3], LABELS[:3], title="Childhood", loc='upper left', 
                    bbox_to_anchor=(0.0, LEGEND_Y), frameon=False, 
                    title_fontproperties={'weight':'bold', 'size':12})
    l2 = ax1.legend(bars[3:5], LABELS[3:5], title="Adulthood", loc='upper left', 
                    bbox_to_anchor=(0.12, LEGEND_Y), frameon=False, 
                    title_fontproperties={'weight':'bold', 'size':12})
    l3 = ax1.legend(bars[5:], LABELS[5:], title="Aged", loc='upper left', 
                    bbox_to_anchor=(0.25, LEGEND_Y), frameon=False, 
                    title_fontproperties={'weight':'bold', 'size':12})
    ax1.add_artist(l1); ax1.add_artist(l2)

    ax1.set_title('A. Global Lifetime Heatwave Exposure (Peak-and-Decline Trajectory)', 
                  loc='left', fontsize=16, fontweight='bold', pad=80)
    ax1.set_ylabel('Lifetime Exposure Days', fontsize=13)

    # --- 5. Panel B: Aged Stage Specific Exposure ---
    ax2.bar(x, aged_exposure, width=X_WIDTH, color='#bd0026', 
            edgecolor='white', lw=0.5)
    ax2.errorbar(x, aged_exposure, yerr=aged_errors, fmt='none', 
                 ecolor='#333333', elinewidth=1.2, capsize=4, alpha=0.7)

    aged_patch = mpatches.Patch(color='#bd0026', label='Ages 60-75')
    ax2.legend(handles=[aged_patch], title="Stage Focus", loc='upper left', 
               bbox_to_anchor=(0.0, 1.15), frameon=False, 
               title_fontproperties={'weight':'bold', 'size':12})

    ax2.set_title('B. Exposure during Senior Years (Aged Stage)', 
                  loc='left', fontsize=16, fontweight='bold')
    ax2.set_ylabel('Exposure Days', fontsize=13)
    ax2.set_xlabel('Birth Cohort (Year)', fontsize=13)

    # --- 6. Final Details ---
    for ax in [ax1, ax2]:
        ax.spines[['top', 'right']].set_visible(False)
        ax.set_xticks(x)
        plt.setp(ax.get_xticklabels(), rotation=45, ha='right', rotation_mode='anchor')
        ax.grid(axis='y', linestyle='--', alpha=0.3)

    plt.tight_layout()
    plt.savefig('Figure_3_Lifetime_Combined.pdf', bbox_inches='tight')
    plt.show()

if __name__ == "__main__":
    main()
